apiVersion: v1
kind: Service
metadata:
  name: harness-ci-lab
  labels:
    app: harness-ci-lab
spec:
  selector:
    app: harness-ci-lab
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP